Add option to mask coreos metadata sshkeys service
Masking `coreos-metadata-sshkeys@core.service` on `master` and `worker`
nodes to avoid flooding logs with:
```
Error: failed to update authorized keys
Caused by: update-ssh-keys: no keys found in "/home/core/.ssh/authorized_keys.d"
coreos-metadata-sshkeys@core.service: Control process exited, code=exited, status=1/FAILURE
coreos-metadata-sshkeys@core.service: Failed with result 'exit-code'.
```